version: '3'

services:

  rabbitmq:
    container_name: jynx-rabbit-mq
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - jynx-network
    environment:
      RABBITMQ_DEFAULT_USER: jynx-username
      RABBITMQ_DEFAULT_PASS: jynx-password
      RABBITMQ_DEFAULT_VHOST: jynx

  postgredb:
    image: postgres:alpine
    container_name: jynx-postgre-db
    restart: always
    environment:
      POSTGRES_PASSWORD: jynx-password
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - jynx-network

networks:
  jynx-network:
    driver: bridge