version: '3'

services:

  rabbitmq:
    container_name: jynx-rabbit-mq
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - jynx-network
    environment:
      RABBITMQ_DEFAULT_USER: usr_jynx
      RABBITMQ_DEFAULT_PASS: pass_jynx
      RABBITMQ_DEFAULT_VHOST: jynx

  mysql:
    image: mysql:5.7
    container_name: jynx-mysql
    restart: always
    environment:
      MYSQL_DATABASE: jynx
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: jynx
      MYSQL_PASSWORD: jynx
    ports:
      - 3306:3306
    networks:
      - jynx-network

networks:
  jynx-network:
    driver: bridge