# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Jynx Build Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: jynx-db
          POSTGRES_PASSWORD: jynx-password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      # Label used to access the service container

      rabbitmq:
        # Docker Hub image
        image: rabbitmq:3-management-alpine
        # Provide the password for rabbitmq
        ports:
          - "5672:5672"
        env:
          RABBITMQ_DEFAULT_USER: jynx-username
          RABBITMQ_DEFAULT_PASS: jynx-password
          RABBITMQ_DEFAULT_VHOST: jynx
           
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
